Metamask wallet connection and sign-in flow
ndau/npay-dao pull request #1
Opened 2024-04-02 06:54 UTC by AliBhutta2073

2024-04-03 12:07 UTC, moneta commented on backend/src/socket/ndauConnect.js
>      console.log(socket.id);
Please just rename the file name ndauConnect to, says, walletConnect or something similar

2024-04-03 12:14 UTC, moneta requested changes

2024-04-03 12:14 UTC, moneta commented on frontend/src/Components/buttons/connect_metamask_button.jsx
> +            socket.on(
We should get rid of these sockets

2024-04-03 12:14 UTC, moneta commented on frontend/src/Components/VoteButton/VoteButton.tsx
> +        signature
This should be the signature against the complete payload, not the sign-in signature. The signature should use  typed struct V4

2024-04-05 14:38 UTC, AliBhutta2073 commented
Closing, will create a new PR with changes.

2024-04-05 14:38 UTC, closed without merging